name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o codigo
        uses: actions/checkout@v4.2.2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: rafajahn123/fake-shop-desafio:v1
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - run: echo "obter Codigo"
      - run: echo "Configurar o kubeconfig"
      - run: echo "Executar o apply"
